### ISSUE TITLE
Server's returning status code 500

### ISSUE THREAD

**Issue by sundaramgupta** [marcorichetta/cs50w-project2#3]
Although when I ran the application for the first time on the local machine it worked fine, after reconnecting to the server trying to sign up again it's returning a status code of 500. 

![issue marco](https://user-images.githubusercontent.com/50690766/85982809-11d48f80-ba04-11ea-9331-d7057124df2a.png)

**Comment by marcorichetta** [comment]
Could you provide the steps you made?

**Comment by sundaramgupta** [comment]
As in how did I set up the app? 
1. I went to the directory
2. set FLASK_APP=application.py (windows)
3. flask run 

As I'm already working on the same project of mine, I have all the requirements pre-installed.

**Comment by marcorichetta** [comment]
I think the error is due to the fact that you ran flask and then you went **directly** to the url `chanells/undia` but that url works only after you create the channel. 

This is a limitation or bug from my code. It would be nice to redirect to the user creation if it's the first time you enter the app.

Look at the terminal where you ran flask to see a more detailed error a share it here.

**Comment by sundaramgupta** [comment]
That is the thing, I didn't go to the URL `channels/unida` I got redirected to it as soon as I opened the localhost (maybe because when I singed up the last time, I created and joined that channel with the same username that I used this time and did not leave the channel before closing the window).

 I already checked the terminal, it said `key error:  channels/undia`.

**Comment by marcorichetta** [comment]
The last channel you visited is saved in your browser's localStorage so when you re open the page it will redirect to that last channel.

The thing is, when you restart flask all the channels are erased so you are being redirected to an nonexistent channel.

Erase your browser's localStorage when you restart your app or put some sort of check for this condition.

**Comment by sundaramgupta** [comment]
It's working now. Thanks

**Comment by sundaramgupta** [comment]
It's working now. Thanks
