### ISSUE TITLE
create.html

### ISSUE THREAD

**Issue by aswinantony** [marcorichetta/cs50w-project2#4]
Hi, 

I can see that you have used a template named "create.html" but it's missing in the **templates** directory.

**Comment by marcorichetta** [comment]
I actually left that because at the beginning I used the '+ Create' button to go to `/create`.
Then I realized I could reuse the `index.html` template.

I removed that section on the last commit.
Thanks for spotting the error!

**Comment by aswinantony** [comment]
Thanks for explaining.
